- hosts: all
  vars:
    go_version: "1.22.1"
    go_checksum: "aab8e15785c997ae20f9c88422ee35d962c4562212bb0f879d052a35c8307c7f"
    sftp_enabled: true
  roles:
    - geerlingguy.go
    - devsec.hardening.ssh_hardening
  tasks:
    - name: enable amazon extras
      ansible.builtin.shell: amazon-linux-extras install epel -y

    - name: Install fail2ban
      ansible.builtin.package:
        name: fail2ban
        state: present
        update_cache: true

    - name: enable fail2ban
      ansible.builtin.shell: |
        cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
        sed -i "s/^\[sshd\]/[sshd]\nenabled=true/" /etc/fail2ban/jail.local
        systemctl restart fail2ban
        systemctl enable fail2ban

    - name: Install git
      ansible.builtin.package:
        name: git
        state: present

    - name: Create app dir
      ansible.builtin.file:
        path: /usr/local/unicorn_reporter
        state: directory
        mode: '0755'

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: https://github.com/unicorn-rentals-04/unicorn-trading.git
        dest: /usr/local/unicorn-trading

    - name: Copy backend files to unicorn_reporter
      ansible.builtin.copy:
        src: /usr/local/unicorn-trading/backend/
        dest: /usr/local/unicorn_reporter/
        remote_src: yes

    - name: go init
      ansible.builtin.shell: source ~/.bash_profile; go mod init unicorn_reporter
      args:
          chdir: /usr/local/unicorn_reporter/
      ignore_errors: yes

    - name: go tidy
      ansible.builtin.shell: source ~/.bash_profile; go mod tidy
      args:
          chdir: /usr/local/unicorn_reporter/

    - name: build go binary
      ansible.builtin.shell: source ~/.bash_profile; go build
      args:
          chdir: /usr/local/unicorn_reporter/
      environment:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

    - name: Write Config file
      blockinfile:
        path: /etc/unicorn_reporter_backend.conf
        create: true
        state: present
        owner: root
        group: root
        mode: 0600
        block: |
          ECOMM_BUCKET={{ ecomm_reporter_bucket }}
          ECOMM_STATICREGION={{ ecomm_reporter_bucket_region }}
          ECOMM_OBJECTSTORAGEENDPOINT={{ ecomm_reporter_object_storage_endpoint }}
          START_MODE=REPORTER

    - name: Write systemd config file
      blockinfile:
        path: /etc/systemd/system/unicorn_reporter_backend.service
        create: true
        state: present
        block: |
          [Unit]
          Description=eCommerce Reporter Frontend

          [Service]
          EnvironmentFile=/etc/unicorn_reporter_backend.conf
          PIDFile=/var/run/unicorn_reporter-backend.pid
          Restart=always
          KillSignal=SIGQUIT
          WorkingDirectory=/usr/local/unicorn_reporter
          ExecStart=/usr/local/unicorn_reporter/unicorn_reporter

          [Install]
          WantedBy=multi-user.target

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: unicorn_reporter_backend.service
        enabled: yes
        state: started

- hosts: all
  become: yes
  vars:
    deploydb: "{{ deploy_reporter_database }}"
    mysql_root_password: "{{ ecomm_database_pass }}"
    mysql_databases:
      - name: "{{ ecomm_database_name }}"
    mysql_users:
      - name: "{{ ecomm_database_user }}"
        host: "%"
        password: "{{ ecomm_database_pass }}"
        priv: "orders.*:ALL"
  roles:
    - role: geerlingguy.mysql
      when: deploydb
  tasks:
    - name: Download Sample Data
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/unicorn-rentals-04/unicorn-trading/refs/heads/main/deploy/resources/database/dump.sql
        dest: /var/tmp
        mode: 0777
      when: deploydb

