- hosts: all
  tasks:
    - name: udpate
      apt:
        upgrade: yes
        update_cache: yes

- hosts: all
  roles:
    - geerlingguy.nodejs
    - devsec.hardening.ssh_hardening
  vars:
    sftp_enabled: true
  tasks:
    - name: Install fail2ban
      ansible.builtin.package:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Install git
      ansible.builtin.package:
        name: git
        state: present
        update_cache: yes

    - name: Create app dir
      ansible.builtin.file:
        path: /usr/local/unicorn_rentals
        state: directory
        mode: '0755'

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: https://github.com/unicorn-rentals-04/unicorn-trading.git
        dest: /usr/local/unicorn-trading

    - name: Copy frontend files to unicorn_rentals
      copy:
        src: /usr/local/unicorn-trading/frontend
        dest: /usr/local/unicorn_rentals
        remote_src: yes

    - name: Write react env file
      blockinfile:
        path: /usr/local/unicorn_rentals/frontend/.env
        create: true
        state: present
        block: |
          REACT_APP_ECOMM_IP={{ ecomm_ip }}

    - name: Install packages based on package.json.
      community.general.npm:
        path: /usr/local/unicorn_rentals/frontend

    - name: Install serve
      community.general.npm:
        name: serve
        global: true

    - name: build production
      ansible.builtin.shell: . /home/ubuntu/.profile && npm run build
      args:
          chdir: /usr/local/unicorn_rentals/frontend

    - name: Write Config file
      blockinfile:
        path: /etc/unicorn_rentals_frontend.conf
        create: true
        state: present
        owner: root
        group: root
        mode: 0600
        block: |
          ECOMM_AUTHTOKEN={{ ecomm_auth_token }}
          ECOMM_APPBUILDPATH=/usr/local/unicorn_rentals/frontend
          ECOMM_ENDPOINT=http://{{ ecomm_reporter_endpoint }}:9999
          ECOMM_DATABASEHOST={{ ecomm_database_host }}
          ECOMM_DATABASEPORT={{ ecomm_database_port | default("3306") }}
          ECOMM_DATABASENAME={{ ecomm_database_name }}
          ECOMM_DATABASEUSER={{ ecomm_database_user }}
          ECOMM_DATABASEPASS={{ ecomm_database_pass }}
          REACT_APP_ECOMM_IP={{ ecomm_ip }}
          ECOMM_REPORTERENDPOINT=http://{{ ecomm_reporter_endpoint }}:9999
          PORT=8080

    - name: Write systemd config file
      blockinfile:
        path: /etc/systemd/system/unicorn_rentals_frontend.service
        create: true
        state: present
        block: |
          [Unit]
          Description=eCommerce Reporter Frontend

          [Service]
          EnvironmentFile=/etc/unicorn_rentals_frontend.conf
          PIDFile=/var/run/unicorn_rentals-frontend.pid
          Restart=always
          KillSignal=SIGQUIT
          WorkingDirectory=/usr/local/unicorn_rentals/frontend
          ExecStart=serve -s build

          [Install]
          WantedBy=multi-user.target

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: unicorn_rentals_frontend.service
        enabled: yes
        state: started

- hosts: all
  vars:
    go_version: "1.22.1"
    go_checksum: "aab8e15785c997ae20f9c88422ee35d962c4562212bb0f879d052a35c8307c7f"
  roles:
    - geerlingguy.go
  tasks:
    - name: Create app dir
      ansible.builtin.file:
        path: /usr/local/unicorn_rentals
        state: directory
        mode: '0755'

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: https://github.com/unicorn-rentals-04/unicorn-trading.git
        dest: /usr/local/unicorn-trading

    - name: Copy backend files to unicorn_rentals
      ansible.builtin.copy:
        src: /usr/local/unicorn-trading/backend/
        dest: /usr/local/unicorn_rentals/backend
        remote_src: yes

    - name: go init
      ansible.builtin.shell: bash -l -c " go mod init unicorn_rentals"
      args:
        chdir: /usr/local/unicorn_rentals/backend
      ignore_errors: yes

    - name: go tidy
      ansible.builtin.shell:  bash -l -c "go mod tidy"
      args:
        chdir: /usr/local/unicorn_rentals/backend

    - name: build go binary
      ansible.builtin.shell: bash -l -c "go build"
      args:
        chdir: /usr/local/unicorn_rentals/backend
      environment:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

    - name: Write Config file
      blockinfile:
        path: /etc/unicorn_rentals_backend.conf
        create: true
        state: present
        owner: root
        group: root
        mode: 0600
        block: |
          ECOMM_AUTHTOKEN={{ ecomm_auth_token }}
          ECOMM_APPBUILDPATH=/usr/local/unicorn_rentals/backend
          ECOMM_ENDPOINT=http://{{ ecomm_reporter_endpoint }}:9999
          ECOMM_DATABASEHOST={{ ecomm_database_host }}
          ECOMM_DATABASEPORT={{ ecomm_database_port | default("3306") }}
          ECOMM_DATABASENAME={{ ecomm_database_name }}
          ECOMM_DATABASEUSER={{ ecomm_database_user }}
          ECOMM_DATABASEPASS={{ ecomm_database_pass }}

    - name: Write systemd config file
      blockinfile:
        path: /etc/systemd/system/unicorn_rentals_backend.service
        create: true
        state: present
        block: |
          [Unit]
          Description=eCommerce Reporter Backend

          [Service]
          EnvironmentFile=/etc/unicorn_rentals_backend.conf
          PIDFile=/var/run/unicorn_rentals-backend.pid
          Restart=always
          KillSignal=SIGQUIT
          WorkingDirectory=/usr/local/unicorn_rentals/backend
          ExecStart=/usr/local/unicorn_rentals/backend/unicorn_rentals

          [Install]
          WantedBy=multi-user.target

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: unicorn_rentals_backend.service
        enabled: yes
        state: started
